#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        print('true')
    except NameError:
        print(message)
